### ISSUE TITLE
Is there any way to turn off dimming?

### ISSUE THREAD

**Issue by sgbasaraner** [slackhq/PanModal#116]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

Is there any way to turn off dimming? I don't want the presenter to be dimmed.

**Comment by jordanpichler** [comment]
Yup, just set `panModalBackgroundColor` to `.clear` in your implementation of the PanModalPresentable protocol ⬇️

```
    var panModalBackgroundColor: UIColor { .clear }
```

**Comment by sgbasaraner** [comment]
@jordanpichler  Thanks!
