### ISSUE TITLE
PanScrollable of scrollView in WKWebView does not working

### ISSUE THREAD

**Issue by k-lpmg** [slackhq/PanModal#12]
### Description
PanScrollable of scrollView in WKWebView does not working.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

PanModal version: 1.2

iOS version: 12.1

#### Steps to reproduce:
1. I create simple WebViewController that implemented PanModalPresentable
``` swift
import UIKit
import WebKit

import PanModal

final class WebViewController: UIViewController {
    
    private let webView: WKWebView = {
        let webView = WKWebView()
        webView.translatesAutoresizingMaskIntoConstraints = false
        webView.allowsBackForwardNavigationGestures = true
        return webView
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.addSubview(webView)
        webView.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        webView.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        webView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        webView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        
        loadWeb()
    }
    
    private func loadWeb() {
        let request = URLRequest(url: URL(string: "https://github.com/slackhq/PanModal/blob/master/README.md")!)
        webView.load(request)
    }
    
}

extension WebViewController: PanModalPresentable {
    
    var panScrollable: UIScrollView? {
        return webView.scrollView
    }
    
}
```
2. PresentPanModal WebViewController
``` swift
let controller = WebViewController()
presentPanModal(controller)
```

#### Expected result:
PanScrollable panModal webView.

#### Actual result:
Height is zero.

#### Attachments:

1. Default setting.
<img src="https://user-images.githubusercontent.com/15151687/55142890-f9caec00-5180-11e9-9c94-8506b1115564.gif" width="220" height="470">

2. Add longFormHeight for default height is zero. But, panScrollable is not working.
``` swift
extension WebViewController: PanModalPresentable {
    
    var panScrollable: UIScrollView? {
        return webView.scrollView
    }

    var longFormHeight: PanModalHeight {
        return .maxHeight
    }
    
}
```
<img src="https://user-images.githubusercontent.com/15151687/55142933-0fd8ac80-5181-11e9-86de-7fe72fff1832.gif" width="220" height="470">

**Comment by tun57** [comment]
Hi @k-lpmg, thanks for bringing this to our attention and the repro steps. However, I'm not able to reproduce the issue.

Do you have any other additional configurations?
Can you also check that the `panScrollable` `var` is called?

**Comment by tun57** [comment]
Hi @k-lpmg, thanks for bringing this to our attention and the repro steps, it was helpful in getting down to the root of the issue.

The bug is caused when the `scrollView` contentSize is `.zero` at the time of the webView loading the request and the panModal configuration. There are two straight forward ways to fix this:

1) Set `allowsExtendedPanScrolling` to `true`:
```
var allowsExtendedPanScrolling: Bool {
    return true
}
```

_or_

2) call `PanModalSetNeedsLayoutUpdate()` once the request has finished:
```
    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        panModalSetNeedsLayoutUpdate()
    }
```

**Comment by k-lpmg** [comment]
Hi @tun57 
I applied it according to your answer and it worked.
Thanks!
