### ISSUE TITLE
How to use it from top side for alerts?

### ISSUE THREAD

**Issue by wixvii** [slackhq/PanModal#13]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ X] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

Hey, How can I use pan present from top side not bottom on alerting something.

**Comment by tun57** [comment]
Hey @wixvii , unfortunately this library only supports presentation from the bottom of the screen. We don't have any current plans to support presentation from the top.

**Comment by Yoloabdo** [comment]
I just wanna add +1 on this

**Comment by RaghavaNaidu46** [comment]
Still no plans?
