### ISSUE TITLE
Notify when PanModalPresentable is dismissed 

### ISSUE THREAD

**Issue by jasperblues** [slackhq/PanModal#156]
### Description

Notify / delegate when pan modal is dismissed. 

I keep a strong reference to the panModal when it is presented. If it is dismissed programmatically, great, I can nil it out. 

When dismissed by dragging, I would like to know this happened. Currently using a hack: 

```
extension PanModalPresentationAnimator {

    @objc func animationEnded(_ transitionCompleted: Bool) {
        if let overlay = rootController.overlayController {
            let presented = overlay.view.superview != nil
            if !presented {
                rootController.overlayController = nil
            }
        }
    }

}
```

## Question: 

Will you consider a PR to notify, delegate or invoke a closure when the panModal is dismissed? If yes, which is preferred? 

NB: I see the that there are hooks (`panModalWill/DidDismiss()` on the panModal VC itself, reason not to use these is would lead to repetition of boiler-plate code. PanModalPresentables are presented from a Root (containment) VC as one of the supported navigation/transition schemes in the app. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [X] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [X] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by ppamorim** [comment]
I have the same issue, I will try to sort this out in my fork.

**Comment by ppamorim** [comment]
@jasperblues Here we go: https://github.com/ppamorim/PanModal/pull/7

Just setup your dependency manager to get source code from my fork.

**Comment by ppamorim** [comment]
@jasperblues You can use the flag `fromGestureRecognizer` from the delegate functions `panModalWillDismiss` and `panModalDidDismiss`.

**Comment by jasperblues** [comment]
@ppamorim That looks super useful, however for my case: `PanModalPresentable` VCs are presented from a Root (containment) VC as one of the supported navigation/transition schemes in the app, via a view coordinator / mediator. 

So rather than have all of the `PanModalPresentables` repeat this boiler-plate code, I want to hook it at the root level, either via a notification or callback function when presenting. 

Does it make sense? Sorry I didn't explain it better the first time.

**Comment by ppamorim** [comment]
@jasperblues You can create a extension based on `PanModalPresentable+Defaults`. In this extension you can introduce a default implementation. Example:

```swift
let handlers: [(UIViewController) -> Void] = []

extension UIViewController: PanModalPresentable {
  
  public func panModalDidDismiss(fromGestureRecognizer: Bool) {
    handlers.append(self)
  }

}
```

I hope this helps you.

**Comment by jasperblues** [comment]
Hi @ppamorim Yes, I was thinking along these lines after as I added those extra details for you. I guess this is a reasonable universal solution, for anyone wants to do the same, so I'll close this issue too. Thanks!

**Comment by ppamorim** [comment]
@jasperblues It's make sense, I did update the code to make it more sensible.
