### ISSUE TITLE
Demo App: Navigation Controller option not working.

### ISSUE THREAD

**Issue by zeusmedina** [slackhq/PanModal#16]
Hi there, this project looks great. Awesome work. 
Was just fiddling around with the demo app provided and noticed that the navigation controller option doesn't appear to be working correctly. If I happen to discover what the cause is, I'll be 
happy to open a PR. But I figured ya'll might have a fix sooner.
![Simulator Screen Shot - iPhone 8 Plus - 2019-04-04 at 11 33 50](https://user-images.githubusercontent.com/6268514/55572859-37be9780-56ce-11e9-9756-40110695d126.png)

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version:

iOS version:

#### Steps to reproduce:

1. Open demo App
2. Tap User Groups (Navigation Controller)
3. Observe the screen overlay but no nav bar 

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by tun57** [comment]
Thanks for reporting @zeusmedina, this seems to have broken for iOS 10 devices as a result of a recent change we made. The fix has been pushed to master [9456969](https://github.com/slackhq/PanModal/commit/9456969502565affe0e8256778344cea99fa006a)

**Comment by zeusmedina** [comment]
Awesome, thank you!
