### ISSUE TITLE
Add an option to disable panModal dismissal on background view tap

### ISSUE THREAD

**Issue by DevilDimon** [slackhq/PanModal#17]
### Description

Add an option to disable the dismissal of the modal VC on tapping the background. Currently there is no way to prevent dismissal – you can only tap into the process by overriding `panModalWillDismiss()`.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by TosinAF** [comment]
Hi,

Sounds like a great idea. Unfortunately we are only able to support critical bug fixes at this moment.
If you are able to create a PR for this we would be happy to review and get that merged.

Thanks for reporting!
