### ISSUE TITLE
How can I change a background color for the DimmedView?

### ISSUE THREAD

**Issue by pchernovolenko** [slackhq/PanModal#18]
### Description

Looks like it's no way to change the DimmedView background color. It's always black with alpha set to 0.7. How can I change it to white color with alpha set to 0.7?

### What type of issue is this?
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

**Comment by TosinAF** [comment]
Hi,

You can easily do this by creating a fork & changing those values. Unfortunately at this time we can't provide support for new features, only critical bug fixes. 

Cheers.
