### ISSUE TITLE
Support dynamic height when inputting?

### ISSUE THREAD

**Issue by codwam** [slackhq/PanModal#23]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version:

iOS version:

#### Steps to reproduce:

1. Add a textField at the bottom
2. Present ViewController
3. Tapped textField

#### Expected result:

Keyboard should not obscure textField.

**Comment by tun57** [comment]
Hi @codwam,

There are two ways in which I would imagine you could work around this:

1) https://github.com/slackhq/PanModal#updates-at-runtime
Track keyboard changes and expand the modal on display - or collapse on keyboard dismiss. We currently do this in the new iOS emoji picker on slack when you tap "Add Reaction"

2) Wrap your content in a scrollView and adjust the contentInset when the keyboard appears

Let me know if this helps 🙂

Stephen

**Comment by codwam** [comment]
Thanks
