### ISSUE TITLE
Customizable Transition Duration

### ISSUE THREAD

**Issue by mergesort** [slackhq/PanModal#24]
### Description

Describe your issue here.

### What type of issue is this?
- [x] enhancement (feature request)

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

I was really excited to see the addition of a full screen presentation mechanism for PanModal recently. I noticed in the Full Screen example there was a custom spring damping, which seems reasonable, but the animation doesn't feel quite native as a result. The issue isn't the spring damping though, but the fact that the animation duration isn't customizable.

I'd like to request to add an `animationDuration` property to `PanModalPresentable` for use in the modal presentation, that will allow the timing to be customized.

Thanks a lot!

#### Reproducible in:

PanModal version:
1.2.2

iOS version:
Tested on 12.2, but should be all versions that `PanModal` supports.

**Comment by tun57** [comment]
Hey @mergesort,

Glad to hear that you find it useful :D I went ahead and added 
both `transitionDuration` & `transitionAnimationOptions` https://github.com/slackhq/PanModal/commit/0d999396a5e05b95479ad559321bb39f7ccc50ec let me know if this helps!

Stephen

**Comment by mergesort** [comment]
@tun57 Just gave it a shot, works great. Thanks a bunch!
