### ISSUE TITLE
iPad UI/UX

### ISSUE THREAD

**Issue by laohanme** [slackhq/PanModal#26]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [x] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version: 1.2.2

iOS version: 12.2 (Simulator)

#### Steps to reproduce:

Just ran an example from the PanModal repo

#### Expected result:

What you expected to happen
- expected it fully support iPad view

#### Actual result:

What actually happened
- minor UI/UX problem > image below

#### Attachments:
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-05-21 at 11 16 00](https://user-images.githubusercontent.com/18119268/58065965-16e8cd80-7bba-11e9-9159-123e175b387e.png)

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by TosinAF** [comment]
Hi, 

Thanks for reporting this issue in the sample app. We'll take a look over the next few weeks and sort it out. It should only be an issue within the sample app. We currently have no critical bugs within the library itself.

**Comment by rizwan95** [comment]
It still persists. Any fix for this issue?

**Comment by zulfishah** [comment]
Sample code doesn't work on the iPad.

**Comment by vitali36** [comment]
I have the same problem.

**Comment by laohanme** [comment]
This issue still exist

**Comment by rahulVermaSimpplr** [comment]
` let rect = CGRect(x: self.view.bounds.midX, y: self.view.bounds.midY, width: 0, height: 0)
        presentPanModal(rowType.presentable.rowVC, sourceRect: rect)`
        
        use this code in didSelectRow in sample app
