### ISSUE TITLE
How to disable longForm view in dragging up?

### ISSUE THREAD

**Issue by manuelsBTS** [slackhq/PanModal#27]
We have multiple detail screens. all of them have to display as Pin Model style.  However,  Some of them depending a state are expandable or not.  I mean, those not expandable screens are only showed in shortForm style and user is able to drag down to dismiss.  (If user tries to make drag up  shouldn't happen nothing)

'
Working with PanModel 1.02 due to Swift 3

**Comment by tun57** [comment]
Hi @manuelsBTS,

Have you tried to set the `longFormHeight` instead of the `shortFormHeight`? - this should disable the ability to drag upwards

**Comment by manuelsBTS** [comment]
Hi @tun57 

Yes, however, the height is dynamically based on content.  currently the only way to avoid that behavior is adding the same value to **longFormHeight** than **shortFormHeight**

**Comment by TosinAF** [comment]
Hi @manuelsBTS, 

Yes that would be the preferred way to avoid that. The longForm & shortView height should be equal in order to have a single height on presentation.

Let me know if you have any order questions.

Cheers,
Thanks

**Comment by manuelsBTS** [comment]
Hey @TosinAF 

thanks for your answers guys.  Not really. I think that is the solution based on dynamic height heheh
Thanks for everything.
