### ISSUE TITLE
Using Storyboard!

### ISSUE THREAD

**Issue by barHopperSF** [slackhq/PanModal#28]
Hi,
I really like your PanModal customizable presentation. Amazing job. I am new to Xcode and Swift.
I am trying to call a View Controller from Storyboard instead of programmatically. It loads the controller but has transparent background and non of the labels I have show up. I am using the Basic() just to see if I can load it from there.  Do I need to initiate Storyboard somewhere or I am doing something wrong. Any help will much appreciated. Thanks in advance.! 

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [X ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ X] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [ X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version:

iOS version:

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by TosinAF** [comment]
Hi,

We did not build this project to support Storyboards in any way. We have not tested or tried this out. I suspect it would be some work to make that happen unfortunately & we are only committing to fixing critical bugs in the library. 

If you decide to try to make this happen, we are happy to review and get that merged in for others who may want this feature.

Thanks for writing in. Let me know if you have any other questions.

Cheers,
Tosin

**Comment by TosinAF** [comment]
Oh just saw your edited description,

In general, if you are using a storyboard with this library, its going to be a bit difficult. With segues and what not.

For your specific issue, if the background is transparent, you need set a background color on your view & for the labels ensure you have a text color that is not equal to the background color of the view.

For using this library, you are better off creating your view controller in code. Storyboards in general have their limits and working with custom libraries such as PanModal is one of their limits where its easier to do things in code.

**Comment by barHopperSF** [comment]
TosinAF,
Thank you so much for the quick response. I really appreciate it. I was thinking segues myself. I will give it a try.
