### ISSUE TITLE
Horizontal sliding problem

### ISSUE THREAD

**Issue by wwdc14** [slackhq/PanModal#29]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version:latest

iOS version:12.0

#### Steps to reproduce:

1.Add a horizontal scrolling collectionview on the Viewcontroller
2.PanModal also responds to my slip when I slide the collectionView

#### Expected result:

When I slide collectionview, PanModal not respond to my slide

When slide up and down, left and right slide ban

#### Actual result:

What actually happened
Sliding in all directions

#### Attachments:

<img src="https://s2.ax1x.com/2019/06/07/Vwa9MV.gif" width="50%" height="50%" alt="Screenshot Preview" />

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by TosinAF** [comment]
Hi, 

Thanks for the report. I am looking into the issue and will provide an update soon.

**Comment by wwdc14** [comment]
thank! 😁👍

**Comment by TosinAF** [comment]
@wwdc14 we have a fix, 

```public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        return otherGestureRecognizer == panGestureRecognizer
    }```

I'll publish a PR and update shortly, just wanted to unblock you if possible.

**Comment by TosinAF** [comment]
Issue is now resolved 🏁. If you could confirm that this correctly fixes your issue, that would be great!

**Comment by jassimkm** [comment]
Horizontal Collection view doesn't work .

**Comment by chanhdatng** [comment]
I have the same problem, i embedded a collection view into modal but i can interact ( select or scroll) with it? Can you guys give me some solutions???
