### ISSUE TITLE
Behavior of the modal different between devices 

### ISSUE THREAD

**Issue by xGoPox** [slackhq/PanModal#31]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version: 1.2.2

iOS version: 12.2

#### Steps to reproduce:

1. present a panModal view
2. scroll or drag the modal view 
3. nothing is responding except the tap to dismiss

#### Expected result:

I should be able to pan to expand and scroll the scrollView inside the panModal

#### Actual result:

The modal is presented ✅

- iPhone X
pan to expand ✅
scroll ✅

- iPhone 6 Plus
pan to expand ✅
scroll ❌

- iPhone 6
pan to expand ❌
scroll ❌

- iPhone 6 Plus
pan to expand ✅
scroll ❌

- iPhone 6
pan to expand ❌
scroll ❌

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by tun57** [comment]
Hi @xGoPox,

Thanks for filing this bug, could you provide more details on what you're seeing.

Could you also check if setting `allowsExtendedPanScrolling` to `true` fixes the issue.

**Comment by xGoPox** [comment]
thanks @tun57 that was it !

**Comment by xGoPox** [comment]
@tun57 your solution did fix my issue, I did reopen the issue because the latest release 1.2.3 did break the pan gesture and scrolling, everything works fine with 1.2.2 when setting `allowsExtendedPanScrolling` to `true`

**Comment by TosinAF** [comment]
@xGoPox I'm on this, this was my bad to fix #29. Fix incoming shortly.

**Comment by TosinAF** [comment]
Hi @xGoPox. the fix is now in - https://github.com/slackhq/PanModal/commit/f9fedcb597e8e80b4c2b2d4f13be7e8e47a0aaa5

And the cocoapods version bumped. 

Sorry about that & thanks for reporting.
