### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by ciauri** [slackhq/PanModal#33]
### Description

As an iOS developer wanting to use this library, I'd like to be able to take advantage of Xcode 11's iOS SPM support.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

**Comment by TosinAF** [comment]
This is now done. https://github.com/slackhq/PanModal/releases/tag/1.2.6
I am not so familiar with SPM support so let me know if there are any other issues. 

Feel free to reopen.
