### ISSUE TITLE
the demo "User Groups" Gesture is strange

### ISSUE THREAD

**Issue by fero2004** [slackhq/PanModal#34]
### Description

when I Slide up, the view frame Immediately change to the top.

I check the code

this func : handleScrollViewTopBounce(scrollView: UIScrollView, change: NSKeyValueObservedChange<CGPoint>)

let yOffset = scrollView.contentOffset.y

yOffset == 0 and oldYValue > yOffset 

so the frame change

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version:

iOS version:

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by TosinAF** [comment]
Hi, 

Sorry this was a regression that snuck in. This should now be fixed with https://github.com/slackhq/PanModal/commit/f9fedcb597e8e80b4c2b2d4f13be7e8e47a0aaa5

**Comment by fero2004** [comment]
hi,this issue has already fixed.
but I found another issue, 
xcode11beta,simulator, dissmissController has no Animation but device is right.
is Xcode bug？

**Comment by fero2004** [comment]
oh I see, UIView.animate my not run in MainTread
```
UIView.animate(withDuration: transitionDuration,
                           delay: 0,
                           usingSpringWithDamping: springDamping,
                           initialSpringVelocity: 0,
                           options: animationOptions,
                           animations: animations,
                           completion: completion)
```
change to this seems all right
```
        DispatchQueue.main.async {
            UIView.animate(withDuration: transitionDuration,
                           delay: 0,
                           usingSpringWithDamping: springDamping,
                           initialSpringVelocity: 0,
                           options: animationOptions,
                           animations: animations,
                           completion: completion)
            
        }
```

**Comment by TosinAF** [comment]
Hi, 

Thanks for reporting, we haven't started testing on the latest Xcode beta and will be sure to look into this, once we do.

Cheers,
Tosin
