### ISSUE TITLE
Full content display in short form

### ISSUE THREAD

**Issue by ionsilviumihai** [slackhq/PanModal#35]
### Description
I am using your amazing work for displaying a collapsible header table view in 75% of the screen format and also in 100%. I limited the ability to transition between short form and long form only by accessing a draggable top view (scrolling the UITableView towards the top will not pan the container view).

The problem that I am encountering is about being able to display the entire UITableView content in the short form too, for the moment the rest of 25% of the UITableView content is not scrollable and can be accessed only if the user is expanding the UIViewController to the long format. 

Is there a way to know the percentage/height of the current state? It would be great to have this enhancement!

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by TosinAF** [comment]
Hi @ionsilviumihai,

Thanks for reporting this. This sounds like custom behavior that we do not currently support and no not forsee us adding for our own use. 

At this time, we can only fix critical bug fixes or issues. If you are able, we'd be happy for you to add this feature and submit a PR which we will ensure to review promptly.

Apologies that we can't provide more help at this time.

I will say, if you only need one height for the view, for example to display all the content at once, you can make the short form & long height equal to each other. That will give you a singular height on presentation.

Cheers,
Tosin
