### ISSUE TITLE
longFormHeight .maxHeight isn't working with safeAreaLayoutGuide

### ISSUE THREAD

**Issue by petermumford** [slackhq/PanModal#38]
Swift: 5
XCode: 10.2.1
PanModal: 1.2.4

When I set the longFormHeight to use maxHeight the drag indicator always goes behind the status bar. This happen in any iPhone that needs to use the safeAreaLayoutGuide. 

```
presentPanModal( MyController() )
```

```
class MyController: UITableViewController, PanModalPresentable {
  var panScrollable: UIScrollView? {
    return tableView
  }

  var longFormHeight: PanModalHeight {
    return .maxHeight
  }
  
  var shortFormHeight: PanModalHeight {
    return longFormHeight
  }
}
```

<img width="424" alt="Screenshot 2019-07-12 at 12 09 21" src="https://user-images.githubusercontent.com/331905/61124097-edec0700-a49d-11e9-9d99-16dbc73071f4.png">

Let me know if you need any more information from me. Thank you.

**Comment by ste57** [comment]
Hi @petermumford 

Apologies for the delay! Is this still an issue?

Stephen

**Comment by petermumford** [comment]
Hi @ste57 

No problem. However, I need to go back to see what I did for a temporary fix. I'll let you know asap with more details.

**Comment by ste57** [comment]
Closing this out for now - feel free to reopen if the issue persists
