### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions

### ISSUE THREAD

**Issue by egabor** [slackhq/PanModal#39]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

I'm receiving constantly this message: 'Unbalanced calls to begin/end appearance transitions for ...' in the log, when I use UINavigationController with PanModalPresentable.

The log appears each time when a UINavigationController is being shown or dismissed.

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version: 1.2.4

iOS version: 12.3

#### Steps to reproduce:

The simpliest way:

1. Launch your example project.
2. Select from the list this item: 'User Groups (NavigationController)'.
3. See the log messages.

#### Expected result:

No message on the log like this: 'Unbalanced calls to begin/end appearance transitions for ...'

#### Actual result:

This message on the log: 'Unbalanced calls to begin/end appearance transitions for ...'

#### Attachments:

![unbalanced-bug](https://user-images.githubusercontent.com/10037555/61168546-36fc9380-a550-11e9-8a31-2bcc28fc488d.gif)

**Comment by ste57** [comment]
Hi @egabor 

Apologies for the delayed response & thank you for bringing this to our attention. I've gone ahead and fixed this issue here: https://github.com/slackhq/PanModal/pull/52 which should be merged in soon! Turns out, we _were_ in fact making unnecessary appearance calls.

Stephen
