### ISSUE TITLE
deleteRows The UserGroupViewController automatically moves the top 

### ISSUE THREAD

**Issue by XavierLost** [slackhq/PanModal#45]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report
tableView.deleteRows(at: [NSIndexPath(item: indexPath.row, section: 0) as IndexPath], with: .fade)
deleteRows The UserGroupViewController automatically moves the top 
#### Reproducible in:

PanModal version:

iOS version:

#### Steps to reproduce:

1.
2.
3.

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by ste57** [comment]
Thanks for reporting @XavierLost 

Once https://github.com/slackhq/PanModal/pull/56 is merged in, this should be fixed. Closing out the issue for now, feel free to re-open if this persists after merge.

Stephen
