### ISSUE TITLE
PanModal content is shifted to bottom when switching from short to long form on iPhone X models

### ISSUE THREAD

**Issue by Ornolfr** [slackhq/PanModal#46]
### Description

On iPhone X and newer models with safe area bottom insets, the PanModal works incorrectly when changing state from short to long form and vice versa. The issues vary based on the initial position.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

1. When the PanModal starts in short form and is switched to long form, the view content shifts to the bottom. This behavior can be reproduced as many times as possible by switching the states over and over again.
2. When the PanModal starts in long form and then is dismissed and is started again, the content shifts to the bottom. This gets fixed by switching to short form and back to the long form again.

Otherwise, if PanModal was started in long form and gets switched to short form, everything seems to be working fine.

#### Reproducible in:

PanModal version: 1.2.4

iOS version: 12.4.1

#### Steps to reproduce:

Here's the code that can reproduce this issue:

```
class TestViewController: UIViewController, PanModalPresentable {
    
    private var isViewHidden = false
    
    private let hideableViewHeight = UIScreen.main.bounds.height / 2.75
    
    @IBOutlet var labelTitle: UILabel!
    
    @IBOutlet var constraintLabelTitleTop: NSLayoutConstraint!
    
    @IBOutlet var constraintLabelTitleBottom: NSLayoutConstraint!
    
    @IBOutlet var hideableView: UIView!
    
    @IBOutlet var containerTabs: UIView!
    
    @IBOutlet var constraintHideableViewHeight: NSLayoutConstraint!
    
    @IBOutlet var constraintContainerBottom: NSLayoutConstraint!
    
    private lazy var constraintContainerHeight: NSLayoutConstraint = {
        return initializeContainerHeightConstraint()
    }()
    
    var panScrollable: UIScrollView? = nil
    
    var allowsDragToDismiss: Bool = false
    
    var isUserInteractionEnabled: Bool = true
    
    var showDragIndicator: Bool = false
    
    var shortFormHeight: PanModalHeight {
        if isViewHidden {
            return .contentHeight(getShortFormHeight())
        }
        return longFormHeight
    }
    
    var longFormHeight: PanModalHeight {
        return .maxHeight
    }
    
    func shouldRespond(to panModalGestureRecognizer: UIPanGestureRecognizer) -> Bool {
        return false
    }
    
    var backgroundAlpha: CGFloat = 0.38
    
    var springDamping: CGFloat = 0.8
    
    var transitionDuration: Double = 0.4
    
    override func viewDidLoad() {
        super.viewDidLoad()
        observe()
    }
    
    private func initializeContainerHeightConstraint() -> NSLayoutConstraint {
        var height = presentingViewController?.view?.bounds.height ?? UIScreen.main.bounds.height
        height -= view.safeAreaInsets.top
        height -= view.safeAreaInsets.bottom
        height -= constraintLabelTitleTop.constant
        height -= labelTitle.bounds.height
        height -= constraintLabelTitleBottom.constant
        height -= hideableViewHeight
        return NSLayoutConstraint(
            item: containerTabs!,
            attribute: NSLayoutConstraint.Attribute.height,
            relatedBy: NSLayoutConstraint.Relation.equal,
            toItem: nil,
            attribute: NSLayoutConstraint.Attribute.notAnAttribute,
            multiplier: 1,
            constant: round(height)
        )
    }
    
    private func getShortFormHeight() -> CGFloat {
        return constraintContainerHeight.constant +
            labelTitle.bounds.height +
            constraintLabelTitleTop.constant +
            constraintLabelTitleBottom.constant
    }
    
    private func updateConstraints() {
        constraintHideableViewHeight.constant = isViewHidden ? 0 : hideableViewHeight
        if isViewHidden {
            containerTabs.addConstraint(constraintContainerHeight)
        } else {
            containerTabs.removeConstraint(constraintContainerHeight)
        }
        constraintContainerBottom.isActive = !isViewHidden
    }
    
    private func observe() {
        var isFirstTime = true
        /*observable bool field*/.observeNext { hide in
            self.isSignalAnalyzerHidden = hide
            self.updateConstraints()
            self.buttonChart.alpha = hide ? 0.38 : 1.0
            
            if isFirstTime {
                isFirstTime = false
                return
            }
            self.view.setNeedsLayout()
            UIView.animate(
                withDuration: 0.4,
                delay: 0.0,
                usingSpringWithDamping: 0.8,
                initialSpringVelocity: 0.0,
                options: [.curveEaseInOut, .beginFromCurrentState],
                animations: {
                    self.view.layoutIfNeeded()
                },
                completion: nil
            )
            
            self.panModalSetNeedsLayoutUpdate()
            self.panModalTransition(to: self.isViewHidden ? .shortForm : .longForm)
        }
    }
}
```

#### Expected result:

PanModal should not shift its content.

#### Actual result:

PanModal shifts its content to the bottom of the screen.

#### Attachments:

[Video](https://streamable.com/80mkk)

**Comment by ste57** [comment]
Hi @Ornolfr 

Thanks for bringing this to our attention and the attached video, it was helpful to determine the potential problem here. It looks like this is a result of PanModal sizing itself during transitioning. 

Could you override `anchorModalToLongForm` and set it to `false` in the implementing viewController and try again? This should disable the adjustments to it's content.

Let me know if this fixes it for you,
Stephen

**Comment by Ornolfr** [comment]
Hello @ste57 and thank you for your answer! Unfortunately, overriding the `anchorModalToLongForm` didn't affect the issue in any way.

Interestingly enough, updating to iOS 13 fixed the 2nd bug for me (When the PanModal starts in long form and then is dismissed and is started again, the content shifts to the bottom. This gets fixed by switching to short form and back to the long form again.)

**Comment by ste57** [comment]
If the issue is specifically with the tab bar at the bottom of the screen, I would do something like this:

```func willTransition(to state: PanModalPresentationController.PresentationState) {
        panModalAnimate({ [weak self] in
            self?.accessoryBar.frameOrigin.y = 0 (or the safe area bottom anchor)
        })
    }```

Which should prevent the tab bar from shifting it's position with the pan modal transition

**Comment by Ornolfr** [comment]
@ste57 Thank you for your suggestion! It helped me a lot with the issue; after some extensive coding I was able to programmatically shove the tab bar and UITabBarController selected UIViewController view based on the condition when this bug occurred. Anyway, this is more of a workaround so please decide if this issue could be closed.

**Comment by ste57** [comment]
Glad to hear you got it working @Ornolfr 

I'll go ahead and close out this ticket. Feel free to re-open if this becomes an issue again in the future.
