### ISSUE TITLE
how to don't call viewWillAppear when dismiss PanModal viewcontroller

### ISSUE THREAD

**Issue by devikkim** [slackhq/PanModal#47]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ ] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [ ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ ] I've searched for any related issues and avoided creating a duplicate issue.

---
When i dismiss PanModal view controller, i don't want to call viewWillAppear of parent  viewcontroller.

So, i trying to set 
```
panmodalVC.modalPresentationStyle = .overFullScreen

parentVC.presentPanModal(panmodalVC)
```

and when dismiss,

called viewWillAppear of parentVC.

How to apply don't call viewWillAppear of parentVC?

**Comment by ste57** [comment]
Hi @devikkim 

Thanks for the question. Currently, we have appearance transition calls rooted within the PanModal system, so it will call `viewWillAppear` & `viewWillDisappear` on the parent view controller whenever you present a panModal. Before we consider removing them, is there a reason you wouldn't want them to be called? Maybe we can find an alternative here

Stephen
