### ISSUE TITLE
There's no option to pass touches to the underlaying controller

### ISSUE THREAD

**Issue by natalia-osa** [slackhq/PanModal#48]
### Description

If you want to allow the user to interact both with the presenting view controller and the presented view controller, it's impossible currently. Eg if you treat the library as card presenter, you often want to allow the user to interact eg with the map above (example: Google Maps).
Another example is using the library as a notification panel. I believe in most situations you don't want to block the user interface for those 5s (or different value) as the notification is visible.

### What type of issue is this?
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by ste57** [comment]
Hi @natalia-osa 

Thank you for the request. We have thought about supporting pass-through touches within PanModal but ultimately made the decision to keep it lightweight. We are not planning to work on any new features for the library, in the short term, but we may look to add this to our future roadmap.

However, if you feel this is something you need, we encourage forking the library and adding necessary changes.

Thanks,
Stephen

**Comment by natalia-osa** [comment]
Hi,

Thanks for letting me know. I've finally ended with FloatingPanel library, which fulfills those requirements.

Thanks,
Natalia

**Comment by osdnk** [comment]
Hi all,
I did it in my lib somehow (my lib is exporting bindings to RN) 
A bit hacky but it works  ¯\_(ツ)_/¯ 
https://github.com/osdnk/react-native-slack-bottom-sheet/commit/e72d5f1e51d77ee0fe8c3fe4ce826c0b52e00e2e#diff-872ed152deaa4ed95fc370b34abb753eR107
