### ISSUE TITLE
Should the pan modal still be in a popover in a compact layout?

### ISSUE THREAD

**Issue by MaxHasADHD** [slackhq/PanModal#50]
### Description
In the documentation there is a comment about why you are not checking the size classes, but then it mentions `This is essential when transitioning from .popover to .custom on iPad split view`, however I am always seeing a popover on iPad and never seeing this transition from `.popover` to `.custom`. I guess it's a bit confusing if the expected behavior is that it's always a popover on iPad and this comment makes me think there is a workaround such as dismissing the popover and re-presenting as `.custom` or something

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by ste57** [comment]
Hi @MaxHasADHD 

Thanks for the question. The comment in the documentation reflects a feature that we had previously implemented for PanModal. The idea was to support a PanModal popover without actually adding more view code to the library. For: `This is essential when transitioning from .popover to .custom on iPad split view` we're referring to the fact that the presentation iOS API does not currently allow you to use more than one `PresentationController` during a transition (including adaptive functionality). Previously, we had checks for `regular` & `compact` - once the view would transition to a `compact` state (in the case of iPad split view), we would attempt to dismiss the current panModal & replace with the native iOS popover (vice-versa). 

However, this added complications that we didn't anticipate, so we decided to remove support entirely - instead, solely rendering popover for iPad (we felt the panModal didn't scale appropriately to the larger display) & removing any adaptive support for either case, until we were ready to implement our own custom popover.

Hopefully this answers your question?
Stephen

**Comment by ste57** [comment]
Closing out this issue, feel free to re-open if you have more questions on this topic 🙇
