### ISSUE TITLE
When will you update to swift 5.1 ?

### ISSUE THREAD

**Issue by junkhero** [slackhq/PanModal#57]
### Description

When will you update to swift 5.1?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

#### Reproducible in:

PanModal version: 1.0

iOS version: 11.0 ~ 13.x

**Comment by minuscorp** [comment]
Is there any needs for this to be updated to Swift 5.1?

**Comment by TosinAF** [comment]
Hi, The library now supports Swift 5.0. Should that be fine for 5.1 or does it need to be explicitly updated?

**Comment by minuscorp** [comment]
It was working fine with the previous version tbh

**Comment by TosinAF** [comment]
Sounds good. Will close this for now unless any other issues come up.
