### ISSUE TITLE
changing the Height

### ISSUE THREAD

**Issue by embassem** [slackhq/PanModal#59]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

i'd like to change the height when navigating.
 i'm presenting navigation Controller with VC1  as root  with a short height of 350
when some action in VC1 happened it will push VC2 witch should  change the short height to 500 
if push VC3  short height is 400
if pop to VC1 short height is 350 again 
and so on
is this behavior applicable?

**Comment by ste57** [comment]
Hi @embassem,

Yes, this is possible. A brief example is shown here: https://github.com/slackhq/PanModal#updates-at-runtime

`NavigationController` in the sample app may be a good place to try this out. Whenever you're adjusting height values at runtime, you need to call `panModalSetNeedsLayoutUpdate()` in your VC so the new height value is stored.

Let me know if this helps,
Stephen

**Comment by birdmichael** [comment]
@ste57 
how can i change `PanContainerView` height.
some time i want some view alway on the bottom
this is my code 
```
extension ChatCreateContractsViewController :PanModalPresentable {
    var panScrollable: UIScrollView? {
        return self.listTableView
    }
    func willRespond(to panModalGestureRecognizer: UIPanGestureRecognizer) {
        // 顶部手势跟随
        let translatePoint = panModalGestureRecognizer.translation(in: self.bottomView)
        self.bottomView.center = CGPoint(x: bottomView.center.x, y: bottomView.center.y - translatePoint.y)
    }
    
    func willTransition(to state: PanModalPresentationController.PresentationState) {
        print(state)
        var offset: CGFloat = 0
        if state == .longForm {
            offset = OpenLets.screenHeight() - topOffset - 50 - OpenLets.navHeight()
        } else {
            offset = CreateContractsH - OpenLets.navHeight() - 50
        }
        if #available(iOS 11.0, *) {
            offset -= self.view.safeAreaInsets.bottom
        }
        UIView.animate(withDuration: 0.3) {
            self.bottomView.y = offset
        }
    }

}


class ChatCreateContractsNavViewController: NavigationViewController, PanModalPresentable {
    private let createContracts = ChatCreateContractsViewController()
    func willRespond(to panModalGestureRecognizer: UIPanGestureRecognizer) {
        guard topViewController == createContracts else { return }
        createContracts.willRespond(to: panModalGestureRecognizer)
    }
    func willTransition(to state: PanModalPresentationController.PresentationState) {
        guard topViewController == createContracts else { return }
        createContracts.willTransition(to: state)
    }
}

```

i can make the bottomView always on the bottom，but when the animation, don't call `willRespond`.how can i observe `frame`？
or make the ViewController height is same the bottom of the screen 
```
func adjustPresentedViewFrame() {

        guard let frame = containerView?.frame
            else { return }

        let adjustedSize = CGSize(width: frame.size.width, height: frame.size.height - anchoredYPosition)
        let panFrame = panContainerView.frame
        panContainerView.frame.size = frame.size
        
        if ![shortFormYPosition, longFormYPosition].contains(panFrame.origin.y) {
            // if the container is already in the correct position, no need to adjust positioning
            // (rotations & size changes cause positioning to be out of sync)
            adjust(toYPosition: panFrame.origin.y - panFrame.height + frame.height)
        }
        panContainerView.frame.origin.x = frame.origin.x
        presentedViewController.view.frame = CGRect(origin: .zero, size: adjustedSize)
    }
```
`adjustedSize` is work，but when the `PanGesture` will not be modified dynamically.

so，I think the height of the controller should always be inside the screen. Modify height dynamically when changing Y value.

Thank you for your great work.

**Comment by ste57** [comment]
Hi @birdmichael 

For the panModal mechanism to work, we rely on the `PanContainerView` to keep the frame position consistent. You can set `anchorToLongForm` to `false` if you want the height of the panModal to match the height of the `PanContainerView`.

We have a similar view that we keep at the bottom of the panModal, here's the code we usee:

```
    func willRespond(to panGestureRecognizer: UIPanGestureRecognizer) {
        let yPanTraslation = panGestureRecognizer.translation(in: view).y
        accessoryBar.frame.origin.y = max(0, accessoryBar.frame.origin.y + yPanTraslation)
    }

    func willTransition(to state: PanModalPresentationController.PresentationState) {
        panModalAnimate({ [weak self] in
            self?.accessoryBar.frameOrigin.y = 0
        })
    }
```

Let me know if this helps,
Stepheen

**Comment by birdmichael** [comment]
Hi @ste57
Thank you for your helps.
Successful.
But there is a small problem. When i pan， the view still flashing.
![2019-10-12 10-46-22 2019-10-12 10_47_07](https://user-images.githubusercontent.com/12954743/66693669-e5de7600-ecdd-11e9-8f53-6d59e16488ea.gif)

this is my code
```
    func willRespond(to panModalGestureRecognizer: UIPanGestureRecognizer) {
        // 顶部手势跟随
        let yPanTraslation = panModalGestureRecognizer.translation(in: self.bottomView).y
        let offset = OpenLets.screenHeight() - self.topOffset - 50 - OpenLets.navHeight() - OpenLets.bottomSafeHeight()
//        bottomView.frame.origin.y = min(offset, max(0, bottomView.frame.origin.y - yPanTraslation))
        bottomView.frame.origin.y =  max(0, bottomView.frame.origin.y - yPanTraslation)
    }
    
    func willTransition(to state: PanModalPresentationController.PresentationState) {
        print(state)
        panModalAnimate({ [weak self] in
            var offset: CGFloat = 0
            if state == .longForm {
                offset = OpenLets.screenHeight() - (self?.topOffset ?? 0) - 50 - OpenLets.navHeight() - OpenLets.bottomSafeHeight()
            } else {
                offset = CreateContractsH - OpenLets.navHeight() - 50 - OpenLets.bottomSafeHeight()
            }
            self?.bottomView.y = offset
        })

    }
```


Now I have to limit the maximum height.
when i use 
```
let offset = OpenLets.screenHeight() - self.topOffset - 50 - OpenLets.navHeight() - OpenLets.bottomSafeHeight()
bottomView.frame.origin.y = min(offset, max(0, bottomView.frame.origin.y - yPanTraslation))
```
But I don't think this is the right way

**Comment by ste57** [comment]
Hi @birdmichael 

It looks like this only gets triggered when you're initiating the upwards swipe gesture. I imagine you can probably do something like:

```
if yPanTranslation < 0 {
    bottomView.frame.origin.y =  max(0, bottomView.frame.origin.y - yPanTraslation
}
```
I haven't tried this code out, but it looks like you don't want the bottom view moving downwards, so something like this should work for you.

**Comment by birdmichael** [comment]
hi, @ste57 
Thank you for your help~
In addition, there seems to be some problems on the iPad.

**Comment by ste57** [comment]
No problem. I'm going to go ahead and close this out, feel free to re-open if you have any further issues related to height calculations.
