### ISSUE TITLE
failure get controller from self.storyboard?.instantiateViewController

### ISSUE THREAD

**Issue by irfanpule** [slackhq/PanModal#61]
### Description

how do I resolve this failure `Argument type 'ConfirmOrderAlertVC' does not conform to expected type 'PanModalPresentable'` when I call a controller from the storyboard

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---
#### Attachments:
![Screen Shot 2019-10-24 at 00 29 19](https://user-images.githubusercontent.com/11069520/67418868-d1f81580-f5f5-11e9-9c8b-6356c9d49a78.png)

**Comment by ste57** [comment]
Hi @irfanpule 

Have you checked that `ConfirmOrderAlertVC` implements `PanModalPresentable`? See https://github.com/slackhq/PanModal#usage

We also provide limited support for implementation with storyboards: https://github.com/slackhq/PanModal/issues/28#issuecomment-494994054

Let me know if this helps,
Stephen

**Comment by irfanpule** [comment]
Yes, I have implemented it.

Ok, thanks for your answer. I really hope that in the future this package has a lot of support with storyboards

**Comment by irfanpule** [comment]
I found a way to solve this problem.
after set the value on the attribute owned by the controller, then change the `controller` as `PanModalPresentable.LayoutType`

```swfit
let controller = self.storyboard?.instantiateViewController(withIdentifier: "ConfirmationAlertVC") as! ConfirmationAlertVC
controller.viewModel = self.viewModel
let controllerPanModal = controller as PanModalPresentable.LayoutType
self.presentPanModal(controllerPanModal)
```

**Comment by paawandeep** [comment]
I go through this , the problem is I want to push to another view controller , when I call did select row at inside table view it cannot jump , please anyone help

**Comment by irfanpule** [comment]
> I go through this , the problem is I want to push to another view controller , when I call did select row at inside table view it cannot jump , please anyone help

Is there an error message? can you show your code
