### ISSUE TITLE
Add CI to the project

### ISSUE THREAD

**Issue by simdani** [slackhq/PanModal#63]
### Description

I see that this project does not currently use CI. Do you think it would be a good idea to add github actions (it's free for open source) for test running. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [x] question
- [ ] documentation related
- [x] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by ste57** [comment]
Hi @simdani

We have considered this in the past, but ultimately decided against CI as we do not, yet, have extensive test coverage on this library.

**Comment by simdani** [comment]
Fair enough, then I'll close issue for now.
