### ISSUE TITLE
Bottom offset issue 

### ISSUE THREAD

**Issue by vkosmirak** [slackhq/PanModal#64]
### Description

Describe your issue here.

Please taka a look in the bottom. Video:
![ezgif-1-fff75485030e](https://user-images.githubusercontent.com/6514929/67626143-f8b18880-f84f-11e9-80e0-bb714f29c3e6.gif)

From View Hierarchy
![Untitled](https://user-images.githubusercontent.com/6514929/67626117-c142dc00-f84f-11e9-9ef7-851ffc769e25.png)

Pan model has a bottom offset of content, same as in the top, so the user cannot scroll normally to the bottom.

Is it any workaround? Tried this but didn't helped
```
 override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        // Workaround to update contrains after PanModel is shown
        panModalSetNeedsLayoutUpdate()
    }
````

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version: 1.2.4
iOS version: 13.1

#### Steps to reproduce:

1. Has tableView inside PopModel

#### Expected result:

Content should fit normally

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by ste57** [comment]
Hi @vkosmirak

Could you provide the rest of your PanModal configuration?

Stephen

**Comment by ste57** [comment]
Closing out this issue for now, feel free to reopen if this continues to be an issue.

**Comment by vkosmirak** [comment]
Hey @ste57, sorry for late response. Can't find a reopen button, but will describe my scenario here:

Can't align view to the bottom of the poped controller.
Example:
1. Open PanModel Demo
2. AlertViewController.swift
3. Replace coresponeded lines to new:
```
alertView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true

    var shortFormHeight: PanModalHeight {
        return .contentHeight(500)
    }

    var longFormHeight: PanModalHeight {
        return .contentHeight(500)
    }
```
4. What we did here - align `alertView` to the bottom instead of the top
5. The problem is - this view is not visible
![Screen Shot 2019-11-12 at 1 12 39 PM](https://user-images.githubusercontent.com/6514929/68667263-3dc30380-054e-11ea-8ae8-492b9163c804.png)
6. Sometimes we need to align view to bottom, when there is no scroll container inside
And the question is - is there any workaround for that?

**Comment by ste57** [comment]
Hi @vkosmirak

So it looks like `anchorsToLongForm` may be `false` here. Can you make sure this property is set to `true` in the implementing view controller - this should allow you to anchor the alertView to the bottom of the view

**Comment by vkosmirak** [comment]
@ste57 Thanks! This fixed my issue
```
var anchorModalToLongForm: Bool {
   return true
}
```
