### ISSUE TITLE
How to Handle Keyboard ?

### ISSUE THREAD

**Issue by Adiwin** [slackhq/PanModal#69]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report
Thanks for the awesome library.
I have a form type fields inside the PanModal and I want to handle the field (UITextView or UITextField) whenever this field get focus, keyboard will open and this field should be adjusted so that it will get lie above the keyboard.
I'm new to iOS so I don't know the issue in this library or there are other ways to achieve this type of things. Please help

#### Reproducible in:

PanModal version: 1.2.6

iOS version:

#### Steps to reproduce:

1. Put a UITextField or UITextView
2. Click to focus (open a keyboard)

#### Expected result:
Expected to move panmodal so that desired field get focus (above the keyboard)

#### Actual result:

Keyboard overlap on the field

**Comment by ste57** [comment]
Hi @Adiwin,

In this case you can probably increase the height of the panModal when the keyboard is displayed (https://github.com/slackhq/PanModal#updates-at-runtime) Let me know if this helps

Stephen

**Comment by Himanshuarora97** [comment]
Hi @Adiwin , as @ste57 mentioned you can increase or decrease the height at runtime, if you use autolayout inside the panmodal make sure you update the **bottomAnchor** of the view. I've done the same thing in one of my app.

**Comment by fattalgazi** [comment]
Hi @Himanshuarora97 , I have done as you said,

cnstrContainerViewBottom.constant = cnstrContainerViewBottom.constant + kbSize.height - view.safeAreaInsets.bottom

kbSize is the keyboard size. but there is still some gap appears, what I am missing?

**Comment by fattalgazi** [comment]
I changed

```    
var longFormHeight: PanModalHeight {
        return .maxHeightWithTopInset(40)
    }
```

to

```
    var longFormHeight: PanModalHeight {
        return .maxHeightWithTopInset(0)
    }
```

and now, everything works, it solved the problem, but I don't know why.
