### ISSUE TITLE
Why not make panScrollable nil by default?

### ISSUE THREAD

**Issue by Jauzee** [slackhq/PanModal#7]
### Description

As the titles says, is there any reason to not make it nil by default?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by tun57** [comment]
Hey @Jauzee, this was mostly a design choice. We considered defaulting to the top view in the `presentedViewController`’s hierarchy if it was a `UIScrollView` but we also didn’t want `panScrollable` to get lost amongst the other options - especially in the case of the `presentedViewController` being an ordinary `UIViewController` ; pan presenting a `UIViewController` with a child `tableView` and a `nil` defaulted `panScrollable` value would lead to a broken experience. So we felt it best, in this case, not to assume consumer intentions through configuration alone. Hopefully this answers your question.

**Comment by Jauzee** [comment]
Yeah, I got it, thank you very much @tun57 !
