### ISSUE TITLE
Background dimming animation broken

### ISSUE THREAD

**Issue by danqing** [slackhq/PanModal#72]
### Description

After upgrading to the latest PanModal version, showing the pan modal no longer has background dimming animation. That is, while the modal animates up from the bottom, the black transparent background appears instantly without a fade-in effect.

Dismissing works fine: both the modal and the background has an animation for dismissal.

Expected: The dimming background should animate from alpha 0 to 1 when the pan modal is activated.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by KyoheiG3** [comment]
I located the problem.

https://github.com/slackhq/PanModal/blob/1.2.6/PanModal/Controller/PanModalPresentationController.swift#L650

But I'm not sure if I can delete this line.
