### ISSUE TITLE
could you make SwiftUI Example?

### ISSUE THREAD

**Issue by JaeHwanWO** [slackhq/PanModal#73]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version:

iOS version:

#### Steps to reproduce:

1. edit function
2. edit readme

#### Expected result:

We are going to use SwiftUI as Apple suggests, so PanModal should be supporting SwiftUI as well. 

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by ste57** [comment]
Hi @JaeHwanWO 

Thank you for the request. However, we do not have any current plans to provide support/examples of PanModal in Swift UI. This may change in the future, but feel free to update the README if you're able to find a good way to present a pan modal using Swift UI.

**Comment by valexa** [comment]
There should be ways to do it with UIViewControllerRepresentable but its a missed opportunity if you as the creators don't suggest the preferred way to integrate with SwiftUI

**Comment by oliverorav** [comment]
I managed to get it working with SwiftUI, but as my experience with iOS is small can't guarantee it is the best solution. Feel free to make suggestions.

```swift
extension View {
    func presentModal<Content: View>(displayPanModal: Binding<Bool>, @ViewBuilder content: @escaping () -> Content) -> some View {
        self.onChange(of: displayPanModal.wrappedValue) { value in
            let topMostController = self.topMostController()
            if (value && !topMostController.isPanModalPresented) {
                DispatchQueue.main.async {
                    topMostController.presentPanModal(BasicViewController(modalContent: content(), displayPanModal: displayPanModal))
                }
            }
        }
    }
    
    func topMostController() -> UIViewController {
        var topController: UIViewController = UIApplication.shared.windows.filter {$0.isKeyWindow}.first!.rootViewController!
        while (topController.presentedViewController != nil) {
            topController = topController.presentedViewController!
        }
        return topController
    }
   
}
```
And then it could be used in the SwiftUI view:
```swift
@State var displayPanModal: Bool = false
...

            VStack {
                Text("Hello, World! - \(startTime.getDate())")
                    .frame(minWidth: 0, maxWidth: .infinity)
                    .background(Color.yellow)
                
                Text("Hello, World!")
                    .frame(minWidth: 0, maxWidth: .infinity)
                    .background(Color.green)
                
                Button(action: {
                    displayPanModal = true
                }) {
                    VStack {
                        Text("Click here")
                    }
                }
                
                Text("Hello, World!")
                    .frame(minWidth: 0, maxWidth: .infinity)
                    .background(Color.red)
                
            }.presentModal(displayPanModal: $displayPanModal) {
                VStack {
                    Text("I think")
                    Text("this")
                    Text("might work")
                }
            }
```

**Comment by Simbeul** [comment]
> I managed to get it working with SwiftUI, but as my experience with iOS is small can't guarantee it is the best solution. Feel free to make suggestions.
> 
> ```swift
> extension View {
>     func presentModal<Content: View>(displayPanModal: Binding<Bool>, @ViewBuilder content: @escaping () -> Content) -> some View {
>         self.onChange(of: displayPanModal.wrappedValue) { value in
>             let topMostController = self.topMostController()
>             if (value && !topMostController.isPanModalPresented) {
>                 DispatchQueue.main.async {
>                     topMostController.presentPanModal(BasicViewController(modalContent: content(), displayPanModal: displayPanModal))
>                 }
>             }
>         }
>     }
>     
>     func topMostController() -> UIViewController {
>         var topController: UIViewController = UIApplication.shared.windows.filter {$0.isKeyWindow}.first!.rootViewController!
>         while (topController.presentedViewController != nil) {
>             topController = topController.presentedViewController!
>         }
>         return topController
>     }
>    
> }
> ```
> 
> And then it could be used in the SwiftUI view:
> 
> ```swift
> @State var displayPanModal: Bool = false
> ...
> 
>             VStack {
>                 Text("Hello, World! - \(startTime.getDate())")
>                     .frame(minWidth: 0, maxWidth: .infinity)
>                     .background(Color.yellow)
>                 
>                 Text("Hello, World!")
>                     .frame(minWidth: 0, maxWidth: .infinity)
>                     .background(Color.green)
>                 
>                 Button(action: {
>                     displayPanModal = true
>                 }) {
>                     VStack {
>                         Text("Click here")
>                     }
>                 }
>                 
>                 Text("Hello, World!")
>                     .frame(minWidth: 0, maxWidth: .infinity)
>                     .background(Color.red)
>                 
>             }.presentModal(displayPanModal: $displayPanModal) {
>                 VStack {
>                     Text("I think")
>                     Text("this")
>                     Text("might work")
>                 }
>             }
> ```

Are you able to share your BasicViewController? This is almost perfect. Thanks!

**Comment by linhVmodev** [comment]
@Simbeul 
```
class HalfSheetController<Content>: UIHostingController<Content>, PanModalPresentable where Content: View {
    
    var panScrollable: UIScrollView? {
        return nil
    }
    
    var cornerRadius: CGFloat {
        return 20
    }
    
    var shortFormHeight: PanModalHeight {
        return .intrinsicHeight
    }
    
    var longFormHeight: PanModalHeight {
        return .intrinsicHeight
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.panModalSetNeedsLayoutUpdate()
    }
}

struct HalfSheet<Content>: UIViewControllerRepresentable where Content: View {
    private let content: Content

    @inlinable init(@ViewBuilder content: () -> Content) {
        self.content = content()
    }

    func makeUIViewController(context: Context) -> HalfSheetController<Content> {
        return HalfSheetController(rootView: content)
    }

    func updateUIViewController(_: HalfSheetController<Content>, context: Context) {

    }
}
```
And change present to `topMostController.presentPanModal(HalfSheetController(rootView: content()))`
