### ISSUE TITLE
Is there a way to change the modal type on iPad?

### ISSUE THREAD

**Issue by Jsayer7** [slackhq/PanModal#74]
### Description
When running the example project on an iPad, the modals are displayed inside of a popover. Is there a way to change it to a bottom to top vertical modal similar to the iPhone?
Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version: 1.2.6

iOS version: 11.3

#### Steps to reproduce:

1. Launch the example project
2. Build the app for an iPad device (Simulator is fine)
3. Tap on an example

#### Expected result:
The modal is displayed vertically, from bottom to top

#### Actual result:

What actually happened
The modal is displayed in a popover on the top leading edge of the screen. I tried conforming the class to the UIPopoverPresentationControllerDelegate and then setting the modal style to .fullScreen with no luck. 
#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.
![Screen Shot 2019-12-23 at 10 54 16 AM](https://user-images.githubusercontent.com/5124364/71367318-ae5c3780-2572-11ea-9461-c29ca8054eae.png)

**Comment by Nahatakyan** [comment]
In your root view controller add this
```
class ViewController: UIViewController {
    override func present(_ viewControllerToPresent: UIViewController, animated flag: Bool, completion: (() -> Void)? = nil) {
        if let presentableController = viewControllerToPresent as? PanModalPresentable, let controller = presentableController as? UIViewController {
            controller.modalPresentationStyle = .custom
            controller.modalPresentationCapturesStatusBarAppearance = true
            controller.transitioningDelegate = PanModalPresentationDelegate.default
            super.present(controller, animated: flag, completion: completion)
            return
        }
        super.present(viewControllerToPresent, animated: flag, completion: completion)
    }
}
```
then instead of `presentPanModal` just call `present`

**Comment by Jsayer7** [comment]
Verified the suggestion worked. Thank you!

**Comment by umarfarooqnadeem** [comment]
Worked perfect, Thanks @Nahatakyan
