### ISSUE TITLE
Can't scroll on iPad(6th generation) 

### ISSUE THREAD

**Issue by yousongbrave** [slackhq/PanModal#75]
### Description

Hi,
when i display some items in the tableview with panmodal, on some devices, it can scroll to view the items, but on iPad(6th generation), it can not scroll to view the items.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

PanModal version:
1.2.5
iOS version:
iOS 13.1 iPad(6th generation)
#### Steps to reproduce:

1.List items in the tableview
2.Set value of  'anchorModalToLongForm' property to 'true'
3.Scroll the tableview to view the unvisible items

ps: i checked the codes, the 'isPresentedViewAnchored' method return 'false', it seems there is a floating-point precision issue

#### Expected result:

the tableview can scroll

#### Actual result:

the tableview can not scroll

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.
![debuginfo](https://user-images.githubusercontent.com/4002127/71661110-27843780-2d88-11ea-83d3-3e512c4021e7.png)

**Comment by hadongz** [comment]
i also getting similiar issue using iPhone 8 emulator, but on iPhone 11 it's working fine

**Comment by Abdulaziz-si** [comment]
same here using iPhone 8/8+ emulator

**Comment by ramonilho** [comment]
Same here!

**Comment by elmeriz** [comment]
Any update on this? On some devices (simulator or real device), scrolling of the `panScrollable` is disabled when setting `anchorModalToLongForm = true`. I haven't been able to figure out why it works /doesn't work on a particular device...

**Comment by ste57** [comment]
Hi @yousongbrave 

Thanks for reporting this issue & apologies for the delay. For iPad, I would recommend using a native option for presentation; even with PanModal, we revert to using the `.popover` style (see `UIViewController+PanModalPresenter`)

For the floating-point precision issue, that does seem to be a problem. We didn't encounter this ourselves, but I pushed a speculative fix (https://github.com/slackhq/PanModal/pull/83), so I'd be curious to see if the issue still persists.
