### ISSUE TITLE
table view is not selectable 

### ISSUE THREAD

**Issue by israahamed112** [slackhq/PanModal#76]
I putted a table view inside a  ViewController  and when I present the view controller with the panmodal pod
- and then make  this var longFormHeight: PanModalHeight {
        return .contentHeight(contentheight)
      }
-the table is not selectable (didSelectRowAt didn't get called )

**Comment by ste57** [comment]
Hi @israahamed112 

Could you provide more information on this? 
I.e. are the other delegate methods for the tableView called? Do the tableViewCells get highlighted on selection?
