### ISSUE TITLE
Wrong bottomLayoutOffset when root view controller is UITabBarController created by code

### ISSUE THREAD

**Issue by devxoul** [slackhq/PanModal#79]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

[`PanModalPresentable.bottomLayoutOffset`](https://github.com/slackhq/PanModal/blob/1.2.6/PanModal/Presentable/PanModalPresentable+LayoutHelpers.swift#L38) returns wrong value when:

1. the root view controller is a programatically created UITabBarController(A).
2. the tab bar controller(A) has a presented view controller(B) with `modalPresentationStyle = .fullScreen`.
3. the PanModal is presented from the presented view controller(B)

#### Reproducible in:

PanModal version: 1.2.6

iOS version: 13.x

#### Steps to reproduce:

You can simply checkout https://github.com/devxoul/PanModalBottomLayoutOffset and run. You will see the value of `bottomLayoutGuide.length` of `keyWindow.rootViewController` has changed after `AnotherViewController` is presented:

```
[TabBarController] rootViewController.bottomLayoutGuide.length: 34.0
[TabBarController] rootViewController.safeAreaInsets.bottom: 34.0

[TabBarController] Present AnotherViewController

[AnotherViewController] rootViewController.bottomLayoutGuide.length: 0.0
[AnotherViewController] rootViewController.safeAreaInsets.bottom: 34.0
```

#### Expected result:

It should return the proper bottom offset. (e.g. `34.0`)

#### Actual result:

`0.0`

#### Attachments

<img width="1512" alt="Screen Shot 2020-01-22 at 4 11 39 AM" src="https://user-images.githubusercontent.com/931655/72835044-575e9500-3ccd-11ea-86b8-aa4111467167.png">

**Comment by ste57** [comment]
Hi @devxoul 

Apologies for the delay, https://github.com/slackhq/PanModal/pull/84 should fix your issue, let me know if it doesn't & I can take another look
