### ISSUE TITLE
(Share) Extension Compatibility

### ISSUE THREAD

**Issue by james-ff** [slackhq/PanModal#80]
### Description

This Library is not currently compatible with a Share Extension Target

### What type of issue is this?
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Building this library against a share extension target fails and results in the following Swift Compiler Error:

`PanModalPresentable+LayoutHelpers.swift:37:30: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.`

```
return UIApplication.shared.keyWindow?.rootViewController?.bottomLayoutGuide.length ?? 0
```

#### Reproducible in:

PanModal version: 1.2.6

iOS version: 13.3

#### Steps to reproduce:

1. Add Library as a CocoaPods (or other) dependency to a Share Extension Target
2. Build / Run the Share Extension
3. Swift Compiler Error is given

#### Expected result:

Compatibility with Share Extension context (not dependent on `UIApplication`).

Unclear at the moment how crucial the `UIApplication.shared.keyWindow` is to the functionality of this Library

#### Actual result:

Swift Compiler Error

#### Attachments:

![Screenshot 2020-01-23 at 10 09 43](https://user-images.githubusercontent.com/1874352/72975316-8279df00-3dc8-11ea-9b28-d94715330b70.png)

**Comment by ste57** [comment]
Hi @james-ff 

Thanks for reporting & apologies for the delay. This should be fixed by https://github.com/slackhq/PanModal/pull/81 - feel free to re open this issue if it doesn't.
