### ISSUE TITLE
Accessibility  need - add a label to the modal dismiss handle

### ISSUE THREAD

**Issue by ghubaddole** [slackhq/PanModal#86]
E.g. see apple's music app -- when they have a full screen modal, the little handle on top says "Dismiss Player Button" in Voice Over mode.

How do I support this in my app for visually impaired users?

**Comment by ste57** [comment]
Hi @ghubaddole 

Thanks for reporting. Outside of panModal automatically rendering the view in `longForm` and supporting Two-finger scrub to dismiss, we do not support other accessibility features within PanModal.

We felt it wasn't necessary to highlight the drag indicator/dismiss handle as it would be more valuable to let the user know when the [screen has changed](https://developer.apple.com/documentation/uikit/uiaccessibilityscreenchangednotification) so then they can dismiss using the scrub gesture should they need to dismiss.

However if this is something you absolutely need, we can look to add this.
Stephen

**Comment by ste57** [comment]
Closing this out for now, feel free to reopen if you still have issues
