### ISSUE TITLE
panModalWillDismiss doesn't get called correctly

### ISSUE THREAD

**Issue by danqing** [slackhq/PanModal#87]
### Description

I'm not sure if this is a bug or WAI, but it seems `panModalWillDismiss` is only called when it's being tap/panned to dismiss, and not when the `dismiss(animated:)` method is called.

Granted, when the user calls that method they can do whatever they want there, but does it make more sense for the delegate method be called in such cases as well?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] question

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by ste57** [comment]
Hi @danqing 

Thanks for reporting. I've gone ahead and added this [here](https://github.com/slackhq/PanModal/pull/91)

Feel free to reopen this issue if I missed something,
Stephen
