### ISSUE TITLE
NavigationController-based height animation problem

### ISSUE THREAD

**Issue by fattalgazi** [slackhq/PanModal#90]
### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x ] bug
- [x ] question

* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---
Hello, thanks for your amazing job at first. I'm using NavigationController in PanModal,

Whenever I push a new ViewController in navigationController, I set the new height of the PanModal like this:
```
    var setHeightOfNewVC : CGFloat = 400.0

    override func pushViewController(_ viewController: UIViewController, animated: Bool) {
        
        if(viewController.isKind(of: ChangeVoiceEffectViewController.self)){
            self.setHeightOfNewVC = 500
        }else if(viewController.isKind(of: CallRecordSettingsViewController.self)){
            self.setHeightOfNewVC = 267
        }else{
            self.setHeightOfNewVC = 400
        }
        panModalSetNeedsLayoutUpdate()
        panModalTransition(to: .longForm)
        
        super.pushViewController(viewController, animated: animated)
    }
```

and I have this also:

```
    var shortFormHeight: PanModalHeight {
        return .contentHeight(self.setHeightOfNewVC)
    }
    
    var longFormHeight: PanModalHeight {
        return .contentHeight(self.setHeightOfNewVC)
    }
````

and also when I'm navigating back in navigationController, I use this code to set the height of the PanModal to it's default:

```
    override func popViewController(animated: Bool) -> UIViewController? {
        self.setHeightOfNewVC = 400
        panModalSetNeedsLayoutUpdate()
        panModalTransition(to: .shortForm)
        let vc = super.popViewController(animated: animated)
        return vc
    }
```

Everything works fine, I can set height of PanModal manually across the presented View Controllers and navigating back, but the problem is ; The smooth animation is happening whenever I set the newHeight than bigger the previous height, but if the newHeight is smaller than the previous height, then no animation is happening. 

Please see the video : https://i.imgur.com/OWrL6fX.mp4

Thanks in advance

**Comment by ste57** [comment]
Hi @fattalgazi

Thanks for the report. So although this experience is far from ideal, it's a result of the underlying layout system. There are 2 easy ways to get around this: 

1) Set `anchorModalToLongForm` to false

_OR_

2) Only adjust the `shortFormHeight` value and set `longFormHeight` as `.maxHeight` (or the max value that any child vc could be). Then replace use of `panModalTransition(to: .longForm)` with `panModalTransition(to: .shortForm)`

Context: When adjusting the `longFormHeight` while `anchorModalToLongForm` is true, the layout system cuts off the bottom of the view _without_ animation as a fail-safe

Let me know if this helps,
Stephen

**Comment by fattalgazi** [comment]
Set anchorModalToLongForm to false

this worked perfectly, thank you so much 👍 💯
