### ISSUE TITLE
Push a Controller over current PanModal

### ISSUE THREAD

**Issue by LeeJoey77** [slackhq/PanModal#96]
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/PanModal/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

How to push a controller over current panmodal. For example, when click an avatar in comment lists, it will push a new controller
![未标题-1](https://user-images.githubusercontent.com/34692362/79631089-30f3ad00-8189-11ea-84c8-29c0a1ca00d2.jpg)

**Comment by LeeJoey77** [comment]
forget it

**Comment by dorucojocaru059** [comment]
@LeeJoey77 did you find a solution? If so, what was that ?

**Comment by lidian6864677** [comment]
@LeeJoey77   did you find a solution? If so, what was that ?
